name: Deploy

on:
    workflow_dispatch:
    schedule:
        - cron: '0 8 * * *' 

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                environment: [warp_eng-api-ci, vela_sphinx, warp_sphinx]
        environment: ${{ matrix.environment }}
        env:
            COSMOTECH_API_URL: ${{ secrets.COSMOTECH_API_URL }}
            SERVER_URL: ${{ secrets.SERVER_URL }}
            COSMOTECH_CLIENT_ID: ${{ secrets.COSMOTECH_CLIENT_ID }}
            COSMOTECH_CLIENT_SECRET: ${{ secrets.COSMOTECH_CLIENT_SECRET }}
            REALM_NAME: ${{ secrets.REALM_NAME }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            - uses: astral-sh/setup-uv@v6
            - run: |
                uv venv
                source .venv/bin/activate
                uv pip install .
                python3 -m run.main
